version: '2'
services:
  streaming-server:
    image: 'illuspas/node-media-server'
    container_name: nms
    ports:
      - '1935:1935'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - --videopath=/tmp/videos
      - --rtmp-stream-url=rtmp://nms:1935/live/mystream
    ports:
      - 5001:5001
    volumes:
      - ./server.py:/app/server.py
      - ./static:/app/static
      - ./modules:/app/modules
      - ./videos:/tmp/videos:rw
    environment:
      - WATCHFILES_FORCE_POLLING=true
