version: '2'
services:
  streaming-server:
    image: 'illuspas/node-media-server'
    container_name: nms
    ports:
      - '1935:1935'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - --videopath=/tmp/videos
      - --rtmp-stream-url=rtmp://nms:1935/live/mystream
      # uncomment the below to test an interlude. a file called
      # interlude.mp4 must exist in this project in the `videos` folder.
      # there is an unresolved bug where the server doesn't reload
      # while an interlude is playing.
      # - --interlude=/tmp/videos/interlude.mp4
    ports:
      - 5001:5001
    volumes:
      - ./server.py:/app/server.py
      - ./static:/app/static
      - ./modules:/app/modules
      - ./videos:/tmp/videos:rw
    environment:
      - WATCHFILES_FORCE_POLLING=true
  prometheus:
    image: prom/prometheus:latest
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
